#' Crop video frames to a selected region of interest
#'
#' Crops a list of image frames using ROI coordinates generated by
#' `select_roi()`. The function converts the plotted y-axis coordinates back to
#' EBImage image coordinates before cropping.
#'
#' @param frames A list of image frames, usually loaded from a video.
#' @param roi A list containing `x_min`, `x_max`, `y_min`, and `y_max`
#'   coordinates, usually returned by `select_roi()`.
#'
#' @return A list of cropped image frames. The selected ROI is stored as an
#'   attribute named `roi`.
#'
#' @examples
#' \dontrun{
#' roi <- select_roi(frames, frame_number = 1)
#' cropped_frames <- crop_frames_to_roi(frames, roi)
#' }
#'
#' @export
crop_frames_to_roi <- function(frames, roi) {

  cropped_frames <- lapply(frames, function(img) {

    img_dim <- dim(img)

    # EBImage dimensions are usually: x, y, channel
    img_width  <- img_dim[1]
    img_height <- img_dim[2]

    x_min <- max(1, roi$x_min)
    x_max <- min(img_width, roi$x_max)

    # IMPORTANT:
    # convert plotted Y coordinate to EBImage matrix Y coordinate
    y_min_plot <- roi$y_min
    y_max_plot <- roi$y_max

    y_min_img <- max(1, img_height - y_max_plot + 1)
    y_max_img <- min(img_height, img_height - y_min_plot + 1)

    if (length(img_dim) == 3) {
      img[
        x_min:x_max,
        y_min_img:y_max_img,
        ,
        drop = FALSE
      ]
    } else {
      img[
        x_min:x_max,
        y_min_img:y_max_img
      ]
    }
  })

  attr(cropped_frames, "roi") <- roi

  message("Frames cropped to ROI.")
  message("X: ", roi$x_min, " to ", roi$x_max)
  message("Y plot: ", roi$y_min, " to ", roi$y_max)

  return(cropped_frames)
}
