#' Plot distance from companion tracks over time
#'
#' Creates a summary plot showing the average distance from companion tracks
#' over time. The plot includes the mean companion distance, minimum companion
#' distance, and a ribbon showing variation around the mean distance.
#'
#' @param companion_distance A data frame generated by
#'   `calculate_companion_distance()`. It should contain `time_s`,
#'   `mean_distance`, and `min_distance` columns.
#'
#' @return A `ggplot` object showing companion distance over time.
#'
#' @examples
#' \dontrun{
#' companion_distance <- calculate_companion_distance(
#'   tracks,
#'   fps = 5,
#'   pixel_size = pixel_size_mm
#' )
#'
#' plot_companion_distance(companion_distance)
#' }
#'
#' @importFrom dplyr group_by summarise
#' @importFrom ggplot2 ggplot aes geom_ribbon geom_line theme_classic labs
#' @export
plot_companion_distance <- function(companion_distance) {

  plot_df <- companion_distance %>%
    dplyr::group_by(time_s) %>%
    dplyr::summarise(
      mean_distance = mean(mean_distance, na.rm = TRUE),
      min_distance = mean(min_distance, na.rm = TRUE),
      sd_mean_distance = sd(mean_distance, na.rm = TRUE),
      .groups = "drop"
    )

  ggplot2::ggplot(plot_df, ggplot2::aes(x = time_s)) +
    ggplot2::geom_ribbon(
      ggplot2::aes(
        ymin = mean_distance - sd_mean_distance,
        ymax = mean_distance + sd_mean_distance
      ),
      alpha = 0.2
    ) +
    ggplot2::geom_line(
      ggplot2::aes(y = mean_distance, colour = "Mean"),
      linewidth = 1
    ) +
    ggplot2::geom_line(
      ggplot2::aes(y = min_distance, colour = "Minimum"),
      linewidth = 1
    ) +
    ggplot2::theme_classic(base_size = 12) +
    ggplot2::labs(
      x = "Time (s)",
      y = "Distance from companions",
      colour = NULL,
      title = "Distance from companions over time"
    )
}
